name: github snake

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: generate
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: push to output-snake branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output-snake
          build_dir: dist
          keep_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
